### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by Domosed-gamin** [Jordi735/asciijack#2]
```
ringo@qwerty:~/Загрузки/asciijack-master$ make
g++ -c -O2 src/card.cpp -o bin/card.o
Assembler messages:
Fatal error: can't create bin/card.o: Нет такого файла или каталога
makefile:5: ошибка выполнения рецепта для цели «bin/card.o»
make: *** [bin/card.o] Ошибка 1

```

**Comment by jordi735** [comment]
The bin directory was missing. Added a .gitkeep file to make sure the directory is always pulled in with the rest. Thank you!

**Comment by Domosed-gamin** [comment]
Thank you for fix. Your game is best implementation of blackjack for linux terminal, that i've played. I like ascii art cards.
